(() => {
  const $ = (s) => document.querySelector(s);
  const $$ = (s) => [...document.querySelectorAll(s)];
  const state = {running:false,blackout:false,bpm:128,audio:0,audioCtx:null,analyser:null,stream:null,lastBeat:0,tapTimes:[],autoBpm:false,wakeLock:null,raf:0,demoPhase:0};
  const logEl = $('#log');
  function log(msg,type='info'){const t=new Date().toLocaleTimeString('es-AR',{hour12:false});const line=document.createElement('div');line.className=type;line.textContent=`[${t}] ${msg}`;logEl.prepend(line)}
  function clock(){ $('#clock').textContent=new Date().toLocaleTimeString('es-AR',{hour12:false}) } clock(); setInterval(clock,1000);
  function setStatus(text,ok=true){$('#systemStatus').textContent=text;$('#systemDot').style.background=ok?'var(--ok)':'var(--amber)';$('#systemDot').style.boxShadow=`0 0 12px ${ok?'var(--ok)':'var(--amber)'}`}
  function pulse(power=1){if(state.blackout)return;const layer=$('#strobeLayer');const strobe=Number($('#strobe').value)/100;const master=Number($('#master').value)/100;const opacity=Math.min(.88,(.18+strobe*.55)*power*master);layer.style.opacity=opacity;layer.classList.remove('pulse');void layer.offsetWidth;layer.classList.add('pulse');$$('.fixture').forEach(x=>{x.classList.remove('pulse-fixture');void x.offsetWidth;x.classList.add('pulse-fixture')})}
  function updateStage(level){const master=Number($('#master').value)/100;const sensitivity=Number($('#sensitivity').value)/100;const l=Math.max(0,Math.min(1,level*sensitivity*1.45));state.audio=l;$('#audioMeter').style.width=`${Math.round(l*100)}%`;$('#audioValue').textContent=`${Math.round(l*100)}%`;$('#levelLabel').textContent=`${Math.round(l*100)}%`;$('.nova-core').style.filter=`brightness(${.8+l*1.7}) drop-shadow(0 0 ${10+l*32}px #27dcff)`;$$('.beam').forEach((b,i)=>b.style.opacity=state.blackout?.03:String((.16+l*(.45+i*.05))*master));$$('.fixture').forEach(f=>f.classList.toggle('on',l>.18&&!state.blackout));if($('#pulseToggle').checked&&l>.64&&performance.now()-state.lastBeat>180){state.lastBeat=performance.now();pulse(.65+l*.5)}}
  async function enableAudio(){try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('getUserMedia no disponible');state.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});state.audioCtx=new (window.AudioContext||window.webkitAudioContext)();const src=state.audioCtx.createMediaStreamSource(state.stream);state.analyser=state.audioCtx.createAnalyser();state.analyser.fftSize=1024;state.analyser.smoothingTimeConstant=.68;src.connect(state.analyser);$('#modeBadge').textContent='LIVE AUDIO';$('#modeBadge').className='mode-badge live';setStatus('AUDIO EN VIVO',true);log('Micrófono habilitado · análisis FFT activo','ok')}catch(e){$('#audioReactive').checked=false;$('#modeBadge').textContent='DEMO';$('#modeBadge').className='mode-badge demo';log(`Audio real no disponible: ${e.message}. Continúa modo DEMO.`,'warn')}}
  function disableAudio(){state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;state.analyser=null;state.audioCtx?.close().catch(()=>{});state.audioCtx=null;$('#modeBadge').textContent='DEMO';$('#modeBadge').className='mode-badge demo';log('Audio reactivo desactivado · DEMO interno activo','warn')}
  function audioLoop(){let level=0;if(state.analyser){const arr=new Uint8Array(state.analyser.frequencyBinCount);state.analyser.getByteFrequencyData(arr);const low=arr.slice(1,42);const avg=low.reduce((a,b)=>a+b,0)/(low.length||1)/255;const full=arr.reduce((a,b)=>a+b,0)/(arr.length||1)/255;level=Math.min(1,avg*.78+full*.42)}else if(state.running){const beatHz=state.bpm/60;state.demoPhase+=(Math.PI*2*beatHz)/60;const kick=Math.max(0,Math.sin(state.demoPhase))**10;const texture=(Math.sin(state.demoPhase*.25)+1)*.08;level=.18+texture+kick*.72}updateStage(level);state.raf=requestAnimationFrame(audioLoop)}audioLoop();
  $('#audioReactive').addEventListener('change',e=>e.target.checked?enableAudio():disableAudio());
  $('#pulseToggle').addEventListener('change',e=>log(`Pulse ${e.target.checked?'ON':'OFF'}`,'info'));
  $('#laserToggle').addEventListener('change',e=>{$('#laser').style.display=e.target.checked?'block':'none';log(`Laser virtual ${e.target.checked?'ON':'OFF'}`,'info')});
  $('#fogToggle').addEventListener('change',e=>{$('#fog').style.display=e.target.checked?'block':'none';log(`Fog virtual ${e.target.checked?'ON':'OFF'}`,'info')});
  $('#startBtn').addEventListener('click',()=>{state.running=!state.running;$('#startBtn').textContent=state.running?'■ DETENER SHOW':'▶ INICIAR SHOW';setStatus(state.running?'SHOW EN EJECUCIÓN':'PILOTO LISTO',true);log(state.running?'Show iniciado · motor de escenas activo':'Show detenido','ok')});
  $('#blackoutBtn').addEventListener('click',()=>{state.blackout=!state.blackout;$('#stage').classList.toggle('blackout',state.blackout);$('#blackoutBtn').textContent=state.blackout?'RESTAURAR LUZ':'BLACKOUT';$('#p1State').textContent=state.blackout?'BLACKOUT':'READY';$('#p1State').className=`mode-badge ${state.blackout?'demo':'live'}`;log(state.blackout?'BLACKOUT general activado':'BLACKOUT liberado',state.blackout?'warn':'ok')});
  const sceneMap={cyber:'CYBER',club:'CLUB',cinema:'CINEMA',prisma:'PRISMA',energy:'ENERGY',ambient:'AMBIENT'};
  $$('.scene').forEach(btn=>btn.addEventListener('click',()=>{$$('.scene').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const s=btn.dataset.scene;const stage=$('#stage');stage.className=`stage scene-${s}${state.blackout?' blackout':''}`;$('#sceneLabel').textContent=sceneMap[s];log(`Escena ${sceneMap[s]} cargada`,'ok');pulse(.8)}));
  function setBpm(v){state.bpm=Math.round(v);$('#tempoDisplay').textContent=state.bpm;$('#bpmLabel').textContent=state.bpm;$('#bpmSlider').value=state.bpm}
  $('#bpmSlider').addEventListener('input',e=>setBpm(e.target.value));
  $('#tapBtn').addEventListener('click',()=>{const now=performance.now();state.tapTimes.push(now);if(state.tapTimes.length>6)state.tapTimes.shift();if(state.tapTimes.length>=2){const gaps=state.tapTimes.slice(1).map((t,i)=>t-state.tapTimes[i]);const avg=gaps.reduce((a,b)=>a+b,0)/gaps.length;const bpm=Math.max(60,Math.min(180,60000/avg));setBpm(bpm);log(`TAP BPM → ${state.bpm}`,'info')}pulse(.7)});
  $('#autoBpmBtn').addEventListener('click',()=>{state.autoBpm=!state.autoBpm;$('#autoBpmBtn').textContent=state.autoBpm?'AUTO ✓':'AUTO';log(`Auto BPM ${state.autoBpm?'activo':'desactivado'} (piloto)`,'info')});
  [['master','masterOut','%'],['sensitivity','sensitivityOut','%'],['strobe','strobeOut','%']].forEach(([id,out,suf])=>$('#'+id).addEventListener('input',e=>$('#'+out).textContent=e.target.value+suf));
  [['p1Dimmer','p1DimmerOut'],['p1Pan','p1PanOut'],['p1Tilt','p1TiltOut'],['p1Color','p1ColorOut']].forEach(([id,out])=>$('#'+id).addEventListener('input',e=>{const v=e.target.value;$('#'+out).textContent=v;if(id==='p1Color')$('.nova-symbol').style.filter=`hue-rotate(${v/255*280}deg)`}));
  $('#p1Pulse').addEventListener('click',()=>{pulse(1.45);log('P1 · Bombo fuerte disparado manualmente','ok')});
  $('#p1Reset').addEventListener('click',()=>{const vals={p1Dimmer:180,p1Pan:128,p1Tilt:128,p1Color:160};Object.entries(vals).forEach(([id,v])=>{const el=$('#'+id);el.value=v;el.dispatchEvent(new Event('input'))});log('P1 restablecido a valores seguros','info')});
  $('#fullscreenBtn').addEventListener('click',async()=>{try{if(!document.fullscreenElement){await document.documentElement.requestFullscreen();log('Fullscreen activado','ok')}else{await document.exitFullscreen()}}catch(e){log('Fullscreen no permitido por este navegador','warn')}});
  $('#wakeBtn').addEventListener('click',async()=>{try{if('wakeLock' in navigator){state.wakeLock=await navigator.wakeLock.request('screen');$('#wakeBtn').textContent='☀ ACTIVA ✓';log('Wake Lock activado','ok')}else throw new Error('Wake Lock no disponible')}catch(e){log(e.message,'warn')}});
  async function detectMidi(){const row=$('#midiOutput');if(!navigator.requestMIDIAccess){log('Web MIDI no disponible en este navegador','warn');return}try{const midi=await navigator.requestMIDIAccess();const inputs=[...midi.inputs.values()];row.classList.toggle('online',inputs.length>0);row.querySelector('strong').textContent=inputs.length?`${inputs.length} ENTRADA(S)`:'SIN ENTRADAS';log(inputs.length?`MIDI detectado: ${inputs.map(x=>x.name).join(', ')}`:'Web MIDI disponible, sin dispositivos conectados',inputs.length?'ok':'info');inputs.forEach(input=>input.onmidimessage=e=>{const [status,note,vel]=e.data;if((status&0xf0)===0x90&&vel>0){pulse(vel/90);log(`MIDI note ${note} vel ${vel}`,'info')}})}catch(e){log(`MIDI: ${e.message}`,'warn')}}
  $('#scanBtn').addEventListener('click',async()=>{$('#stage').classList.add('scan');setTimeout(()=>$('#stage').classList.remove('scan'),1000);log('Escaneo universal iniciado','info');await detectMidi();setTimeout(()=>log('Escaneo finalizado · capa virtual P1 y motor visual OK','ok'),700)});
  $('#clearLog').addEventListener('click',()=>{logEl.innerHTML='';log('Log reiniciado','info')});
  function detectDevice(){const ua=navigator.userAgent;const mobile=/Android|iPhone|iPad|Mobile/i.test(ua);const platform=navigator.userAgentData?.platform||navigator.platform||'Desconocida';const cores=navigator.hardwareConcurrency||'?';const mem=navigator.deviceMemory?`${navigator.deviceMemory} GB`:'No expuesta';$('#deviceInfo').innerHTML=`<b>${mobile?'DISPOSITIVO MÓVIL':'PC / DESKTOP'}</b><br>Plataforma: ${platform}<br>CPU lógica: ${cores} · RAM reportada: ${mem}<br>Viewport: ${innerWidth}×${innerHeight} · DPR ${devicePixelRatio}`;const caps=[['Web Audio',!!(window.AudioContext||window.webkitAudioContext)],['Mic',!!navigator.mediaDevices],['Fullscreen',!!document.documentElement.requestFullscreen],['Wake Lock','wakeLock' in navigator],['Web MIDI',!!navigator.requestMIDIAccess],['WebGL',!!document.createElement('canvas').getContext('webgl')]];$('#capabilities').innerHTML=caps.map(([n,ok])=>`<span>${ok?'✓':'×'} ${n}</span>`).join('');log(`Dispositivo detectado · ${mobile?'Móvil':'Desktop'} · ${platform}`,'ok')}
  detectDevice();window.addEventListener('resize',detectDevice);setBpm(128);log('NØVA Pilot v0.9 cargado','ok');log('P1 DMX virtual listo · salida física protegida','info');log('Para audio real: activar AUDIO REACTIVE y permitir micrófono','info');
})();